<?php
/**
 * SocietyPress — Softaculous Install Script
 *
 * WHY: This is the heart of the Softaculous integration. When a hosting customer
 * clicks "Install" in their cPanel, Softaculous handles the database creation,
 * file extraction, and domain setup — then calls our __install() function to
 * configure WordPress, activate the SocietyPress plugin and theme, and set
 * initial options.
 *
 * Softaculous provides:
 * - $__settings['softpath']    — install directory on disk
 * - $__settings['softurl']     — public URL of the install
 * - $__settings['softdb']      — database name (already created)
 * - $__settings['softdbuser']  — database username
 * - $__settings['softdbpass']  — database password
 * - $__settings['softdbhost']  — database hostname
 * - Custom form fields: admin_username, admin_pass, admin_email,
 *                        site_name, org_name, org_email
 *
 * @package SocietyPress
 */


/**
 * Main install function — called by Softaculous after files are extracted
 * and the database is created.
 */
function __install() {
    global $__settings, $error;

    $path      = $__settings['softpath'];
    $url       = $__settings['softurl'];
    $db_name   = $__settings['softdb'];
    $db_user   = $__settings['softdbuser'];
    $db_pass   = $__settings['softdbpass'];
    $db_host   = $__settings['softdbhost'];

    $admin_user  = $__settings['admin_username'] ?? 'admin';
    $admin_pass  = $__settings['admin_pass'] ?? '';
    $admin_email = $__settings['admin_email'] ?? '';
    $site_name   = $__settings['site_name'] ?? 'My Genealogical Society';
    $org_name    = $__settings['org_name'] ?? '';
    $org_email   = $__settings['org_email'] ?? '';

    // Validate required fields
    if ( empty( $admin_pass ) ) {
        $error[] = 'Admin password is required.';
        return false;
    }
    if ( empty( $admin_email ) ) {
        $error[] = 'Admin email is required.';
        return false;
    }

    // ----------------------------------------------------------------
    // 1. Generate wp-config.php
    // ----------------------------------------------------------------

    // Fetch salts from WordPress.org
    $salts = sp_soft_fetch_url( 'https://api.wordpress.org/secret-key/1.1/salt/' );
    if ( empty( $salts ) ) {
        // Fallback: generate our own
        $salt_keys = [
            'AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY',
            'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT',
        ];
        $salts = '';
        foreach ( $salt_keys as $key ) {
            $salts .= "define( '{$key}', '" . srandstr( 64 ) . "' );\n";
        }
    }

    $table_prefix = 'wp_';

    $wp_config = "<?php\n";
    $wp_config .= "/**\n * WordPress configuration — generated by SocietyPress installer.\n */\n\n";
    $wp_config .= "define( 'DB_NAME',     '{$db_name}' );\n";
    $wp_config .= "define( 'DB_USER',     '{$db_user}' );\n";
    $wp_config .= "define( 'DB_PASSWORD', '{$db_pass}' );\n";
    $wp_config .= "define( 'DB_HOST',     '{$db_host}' );\n";
    $wp_config .= "define( 'DB_CHARSET',  'utf8mb4' );\n";
    $wp_config .= "define( 'DB_COLLATE',  '' );\n\n";
    $wp_config .= $salts . "\n";
    $wp_config .= "\$table_prefix = '{$table_prefix}';\n\n";
    $wp_config .= "define( 'WP_DEBUG', false );\n\n";
    $wp_config .= "if ( ! defined( 'ABSPATH' ) ) {\n";
    $wp_config .= "\tdefine( 'ABSPATH', __DIR__ . '/' );\n";
    $wp_config .= "}\n\n";
    $wp_config .= "require_once ABSPATH . 'wp-settings.php';\n";

    swrite( $path . '/wp-config.php', $wp_config, true );

    // ----------------------------------------------------------------
    // 2. Run WordPress installation
    // ----------------------------------------------------------------

    // Load WordPress
    define( 'ABSPATH', $path . '/' );
    define( 'WP_INSTALLING', true );
    define( 'WP_SETUP_CONFIG', true );

    // Set request vars that wp-admin/install.php expects
    $_POST['weblog_title']    = $site_name;
    $_POST['user_name']       = $admin_user;
    $_POST['admin_password']  = $admin_pass;
    $_POST['admin_password2'] = $admin_pass;
    $_POST['admin_email']     = $admin_email;
    $_POST['blog_public']     = 1;

    // Load WP minimal environment
    require_once $path . '/wp-load.php';
    require_once $path . '/wp-admin/includes/upgrade.php';

    // Run WP core install
    $result = wp_install( $site_name, $admin_user, $admin_email, true, '', $admin_pass );

    if ( is_wp_error( $result ) ) {
        $error[] = 'WordPress installation failed: ' . $result->get_error_message();
        return false;
    }

    // Set the site URL (Softaculous knows the correct URL)
    update_option( 'siteurl', rtrim( $url, '/' ) );
    update_option( 'home',    rtrim( $url, '/' ) );

    // ----------------------------------------------------------------
    // 3. Activate SocietyPress plugin
    // ----------------------------------------------------------------

    $plugin_file = 'societypress/societypress.php';

    // Make sure plugin file exists
    if ( ! file_exists( $path . '/wp-content/plugins/' . $plugin_file ) ) {
        // Try alternate path — single-file in plugin dir
        if ( file_exists( $path . '/wp-content/plugins/societypress.php' ) ) {
            $plugin_file = 'societypress.php';
        } else {
            $error[] = 'SocietyPress plugin file not found.';
            return false;
        }
    }

    // Activate the plugin
    require_once $path . '/wp-admin/includes/plugin.php';
    $activated = activate_plugin( $plugin_file );

    if ( is_wp_error( $activated ) ) {
        $error[] = 'Plugin activation failed: ' . $activated->get_error_message();
        return false;
    }

    // ----------------------------------------------------------------
    // 4. Activate SocietyPress theme
    // ----------------------------------------------------------------

    $theme_slug = 'societypress';
    $theme = wp_get_theme( $theme_slug );

    if ( $theme->exists() ) {
        switch_theme( $theme_slug );
    }

    // ----------------------------------------------------------------
    // 5. Configure SocietyPress settings
    // ----------------------------------------------------------------

    $settings = get_option( 'societypress_settings', [] );

    if ( ! empty( $org_name ) ) {
        $settings['organization_name'] = $org_name;
    }
    if ( ! empty( $org_email ) ) {
        $settings['organization_email'] = $org_email;
    }

    // Set sensible defaults for a fresh install
    $settings['welcome_email_enabled'] = 1;
    $settings['welcome_email_subject'] = 'Welcome to ' . ( $org_name ?: $site_name ) . '!';

    update_option( 'societypress_settings', $settings );

    // ----------------------------------------------------------------
    // 6. Set up permalink structure
    // ----------------------------------------------------------------

    update_option( 'permalink_structure', '/%postname%/' );
    flush_rewrite_rules();

    // ----------------------------------------------------------------
    // 7. Clean up WordPress defaults
    // ----------------------------------------------------------------

    // Remove "Hello World" post and sample page
    wp_delete_post( 1, true ); // Hello World
    wp_delete_post( 2, true ); // Sample Page

    // Remove default comment
    wp_delete_comment( 1, true );

    // Set timezone to US/Central as a reasonable default for genealogical societies
    update_option( 'timezone_string', 'America/Chicago' );

    // Discourage search engines during setup (admin can change later)
    update_option( 'blog_public', 0 );

    return true;
}


/**
 * Fetch a URL using cURL or file_get_contents.
 *
 * @param string $url The URL to fetch.
 * @return string The response body, or empty string on failure.
 */
function sp_soft_fetch_url( string $url ): string {
    if ( function_exists( 'curl_init' ) ) {
        $ch = curl_init( $url );
        curl_setopt_array( $ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT        => 15,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_SSL_VERIFYPEER => true,
        ] );
        $body = curl_exec( $ch );
        curl_close( $ch );
        return $body ?: '';
    }

    if ( ini_get( 'allow_url_fopen' ) ) {
        $body = @file_get_contents( $url );
        return $body ?: '';
    }

    return '';
}
