<?php
/**
 * Theme Footer
 *
 * WHY: Closes out the page structure opened in header.php. Includes a
 * simple copyright line and the wp_footer() call that WordPress needs
 * for scripts and admin bar functionality.
 *
 * @package SocietyPress
 */
?>

    <footer class="site-footer">
        <p>&copy; <?php echo wp_date( 'Y' ); ?> <?php bloginfo( 'name' ); ?>. All rights reserved.</p>
    </footer>

</div><!-- .site -->

<!-- Search dropdown toggle — vanilla JS, no dependencies.
     WHY here: The DOM must be ready. This is a ~20-line handler — not
     worth a separate .js file. -->
<script>
(function() {
    var wrap   = document.querySelector('.sp-header-search-wrap');
    var toggle = wrap ? wrap.querySelector('.sp-search-toggle') : null;
    var form   = wrap ? wrap.querySelector('.sp-header-search') : null;
    var input  = form ? form.querySelector('input[type="text"]') : null;

    if (!toggle || !form) return;

    toggle.addEventListener('click', function() {
        wrap.classList.add('sp-search-open');
        toggle.setAttribute('aria-expanded', 'true');
        if (input) input.focus();
    });

    // Close when clicking outside the search wrapper
    document.addEventListener('click', function(e) {
        if (!wrap.classList.contains('sp-search-open')) return;
        if (!wrap.contains(e.target)) {
            wrap.classList.remove('sp-search-open');
            toggle.setAttribute('aria-expanded', 'false');
        }
    });

    // Close on Escape key
    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && wrap.classList.contains('sp-search-open')) {
            wrap.classList.remove('sp-search-open');
            toggle.setAttribute('aria-expanded', 'false');
            toggle.focus();
        }
    });
})();
</script>

<!-- User dropdown click/tap toggle — vanilla JS, no dependencies.
     WHY: The CSS :hover dropdown works fine for mouse users, but touch
     devices (phones, tablets, some hybrids) don't reliably fire :hover.
     This adds a click/tap toggle as a parallel mechanism. The CSS :hover
     rules stay intact — this JS just adds/removes a class that the CSS
     also responds to, so both input methods work. -->
<script>
(function() {
    var menu    = document.querySelector('.sp-user-menu');
    var trigger = menu ? menu.querySelector('.sp-user-trigger') : null;

    /* Nothing to do if the user isn't logged in (no trigger exists) */
    if (!trigger) return;

    /* WHY we add aria-expanded here instead of in PHP: The HTML is
       generated by the plugin, so adding it there would require a plugin
       change for a theme-level UX concern. Setting it via JS keeps the
       theme self-contained. */
    trigger.setAttribute('aria-expanded', 'false');

    trigger.addEventListener('click', function(e) {
        /* WHY preventDefault: The trigger is an <a> linking to My Account.
           On touch devices we want the FIRST tap to open the dropdown, not
           navigate away. Desktop mouse users can still hover to see the
           dropdown and click the link to navigate — the click handler only
           toggles the class, so if :hover already shows the dropdown, the
           link still works on the second click. On touch, the first tap
           opens the menu; tapping a menu item navigates. If users want
           My Account, it's in the dropdown. */
        e.preventDefault();

        var isOpen = menu.classList.toggle('sp-user-open');
        trigger.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
    });

    /* Close when clicking/tapping anywhere outside the menu */
    document.addEventListener('click', function(e) {
        if (!menu.classList.contains('sp-user-open')) return;
        if (!menu.contains(e.target)) {
            menu.classList.remove('sp-user-open');
            trigger.setAttribute('aria-expanded', 'false');
        }
    });

    /* Close on Escape key — consistent with the search dropdown behavior */
    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && menu.classList.contains('sp-user-open')) {
            menu.classList.remove('sp-user-open');
            trigger.setAttribute('aria-expanded', 'false');
            trigger.focus();
        }
    });
})();
</script>

<?php wp_footer(); ?>
</body>
</html>
